import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/hompage.module.scss'

export default function Virtual() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NAILS REPUBLIK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Page under maintenance
        </h1>

        <p className={styles.description}>
          <a>Lauch page</a>
          </p>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          {/* Powered by{' '} */}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
            NAILS REPUBLIK
          </span>
        </a>
      </footer>
    </div>
  )
}